#include "gr/world/CanonPlaces.hpp"

//  本文件由 tools/gen_canon_places.py 自动生成，请勿手改。
//  源：《蛊真人两天五域地点总表》（截止第六卷第368节「方源、巨阳战星宿」）。

namespace gr { namespace canon {

const std::vector<CanonPlace>& allPlaces() {
    static const std::vector<CanonPlace> k = {
      {
        "太古白天", "天域／世界层", "太古白天", Domain::None,
        CanonPlace::Kind::TwoHeavens,
        -1.0, -1.0, false,
        "原文未明",
        "宿命大战前已与黑天混淆、合并，后称幽天；太阳亦被幽魂毁灭",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "位于五域之上，与太古黑天同属残存的太古九天",
      },
      {
        "太阳", "天体／极端环境", "太古白天", Domain::None,
        CanonPlace::Kind::TwoHeavens,
        -1.0, -1.0, false,
        "原文仅以“方源暗中估量和巨雄海域差不多”作比较，未给确定数字",
        "第六卷宿命大战期间被幽魂魔尊毁灭",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "沿太古白天的固定东西循环路线运行，路线本应空无一物",
      },
      {
        "天罡气墙", "天然天险／罡气层", "太古白天与太古黑天之间", Domain::None,
        CanonPlace::Kind::TwoHeavens,
        -1.0, -1.0, false,
        "原文未明",
        "中洲三座仙蛊屋曾打通通道强行穿过；后期两天混淆时仍可辨认，但未写明彻底消失",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "横亘于两天之间，中洲蛊仙为突袭北原曾先突破其下层进入黑天",
      },
      {
        "天堑", "白天天然支柱／天道节点", "太古白天", Domain::None,
        CanonPlace::Kind::TwoHeavens,
        -1.0, -1.0, false,
        "原文未明",
        "被幽魂魔尊破坏，属支撑太古白天的目标之一",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "与天柱、天脉节点同为太古白天的支撑结构，具体坐标原文未明",
      },
      {
        "天柱", "白天天然支柱／天道节点", "太古白天", Domain::None,
        CanonPlace::Kind::TwoHeavens,
        -1.0, -1.0, false,
        "原文未明",
        "被幽魂魔尊破坏，促使太古白天迅速被黑天吞并",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "九天相互连接并持续旋转形成的结构，太阳亦在其中运行",
      },
      {
        "天脉节点", "天道节点", "太古白天", Domain::None,
        CanonPlace::Kind::TwoHeavens,
        -1.0, -1.0, false,
        "原文未明",
        "幽魂魔尊针对性摧毁；闪光洞天已毁，华文洞天仍为存续目标",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "原文未给统一坐标；华文洞天、闪光洞天均被认定为节点",
      },
      {
        "华文洞天（洞天内）", "洞天", "太古白天", Domain::None,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "人口比琅琊福地的毛民还多；原文未给面积数字",
        "截至断更仍存续，曾为天庭联盟争取对象，尚未被天庭攻克",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "位于太古白天，具体经纬度原文未明；洞天内环境以信道道痕为主",
      },
      {
        "闪光洞天（洞天内）", "洞天／天脉节点", "太古白天", Domain::None,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "已被幽魂魔尊摧毁，星宿据此推断华文洞天将成为下一个目标",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "太古白天中，具体坐标原文未明",
      },
      {
        "兽灾洞天（洞天内）", "洞天", "太古白天", Domain::None,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "方源为安置十二太古年兽而经营、吞并该洞天，已易主并纳入其体系",
        CanonPlace::Status::ChangedOwner,
        CanonPlace::Evidence::A,
        "太古白天中，具体坐标原文未明；洞天未吞并九天碎片",
      },
      {
        "天庭洞天（洞天内）", "洞天／势力中枢", "中洲上方的太古白天", Domain::None,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文称“空间广阔骇人听闻”，未给数字",
        "仍是天庭与中洲势力的中枢；第五卷大战后作为回缩据点存续",
        CanonPlace::Status::Battlefield,
        CanonPlace::Evidence::A,
        "“位于中洲天上之天”，中洲正中高空，历代天庭成员洞天融合归并而成",
      },
      {
        "宝黄天（洞天内）", "洞天／交易市场", "位置未知，仅知是黄天碎片形成的独立交易市场", Domain::None,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "截至断更仍作为蛊界最大蛊仙交易市场持续运转",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "无人知晓其具体所在；不属于两天中公开可定位的固定区域",
      },
      {
        "太古黑天", "天域／世界层", "太古黑天", Domain::None,
        CanonPlace::Kind::TwoHeavens,
        -1.0, -1.0, false,
        "原文未明",
        "气潮泛滥、太古荒兽横行；后与白天混淆、合并为幽天",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "位于五域之上，与太古白天并列",
      },
      {
        "天罡气墙", "天然天险／罡气层", "太古黑天与太古白天之间", Domain::None,
        CanonPlace::Kind::TwoHeavens,
        -1.0, -1.0, false,
        "原文未明",
        "中洲队伍从黑天下方穿过；并非绝对不可逾越",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "横亘于黑天下缘，与白天一侧相连",
      },
      {
        "安魂洞天（洞天内）", "洞天／人族势力", "中洲上方的太古黑天", Domain::None,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "有至少十处超级魂道资源点；面积原文未明",
        "寒灰仙姑被幽魂占据肉身；两天联盟时期存续，后身份暴露",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "洞天内有迷魂湖；具体坐标原文未明",
      },
      {
        "冰晶洞天（洞天内）", "洞天／雪民势力", "中洲上方的太古黑天", Domain::None,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "冰晶仙王主持两天联盟会晤，仍是黑天异族洞天核心之一",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "中洲上方黑天；洞天内高山由寒晶铸就，最高峰巅有冰雪大殿",
      },
      {
        "夜狼洞天（洞天内）", "洞天／人族势力", "中洲上方的太古黑天", Domain::None,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "夜天狼君暗中通敌投靠天庭，洞天在两天联盟中存续",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "夜天狼君率领夜天狼群活动；具体坐标原文未明",
      },
      {
        "碎骨洞天（洞天内）", "洞天／人族势力", "东海上方的太古黑天", Domain::None,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "骷髅姥姥掌管的黑天人族洞天，参与反对五域人族霸权的联合",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "从安魂洞天出发需经中洲、东海后升入黑天抵达",
      },
      {
        "大智洞天（洞天内）", "洞天／墨人势力", "太古黑天", Domain::None,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "天庭联盟进攻黑天时被率先攻克，成为两天战争转折点",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "具体坐标原文未明，仅知墨人族致力收集乾坤晶壁",
      },
      {
        "乱石洞天（洞天内）", "洞天／石人势力", "太古黑天", Domain::None,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "属冰晶仙王召集的异族洞天联盟成员，截至断更仍存续",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "具体坐标原文未明",
      },
      {
        "弯月洞天（洞天内）", "洞天", "东海上方的太古黑天", Domain::None,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "题干要求覆盖的洞天之一；正文未给其断更节点详细战况，故标存续待考",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "太古黑天，具体坐标原文未明",
      },
      {
        "中洲", "大陆／域", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.5094, 0.4125, false,
        "“绵延亿里”",
        "宿命大战后十大古派撤离，方源随后大掠中洲，天庭收缩于天庭洞天",
        CanonPlace::Status::Battlefield,
        CanonPlace::Evidence::A,
        "五域之一",
      },
      {
        "圣贤界壁", "界壁／天然屏障", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.5031, 0.4125, false,
        "原文称“宽广无比”，未给数值；可斩出七十六步通道",
        "五域界壁奥秘解开后逐渐消失，跨域交流障碍减弱",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "环绕中洲，连接天地；凤九歌等曾选薄弱处突破",
      },
      {
        "地渊", "深谷／深渊", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.5700, 0.5500, true,
        "原文仅称“深不见底”",
        "地貌级地点；截至断更仍是中洲深谷特征地貌",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "中洲内部，具体方位原文未明",
      },
      {
        "飞鹤山", "悬空山／山门", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.4700, 0.6600, true,
        "山峦本身；具体长宽原文未明",
        "仙鹤门公共福地原址；第五卷撤离后整座悬空山彻底消失",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "中洲南部群山，三万丈云海之巅、苍穹之中",
      },
      {
        "仙鹤门大本营", "门派山门／福地", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.5094, 0.4208, false,
        "飞鹤山及公共福地；面积原文未明",
        "福地随山迁移撤离，方源抵达时原址已空",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "位于飞鹤山上，中洲南部",
      },
      {
        "落天河", "河", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::TwoHeavens,
        -1.0, -1.0, false,
        "形成“横贯中洲大陆的第一长河”；源头内陆海洋“亿万顷”",
        "方源收取六成，下游河床裸露、生态与农业受全面影响",
        CanonPlace::Status::Absorbed,
        CanonPlace::Evidence::A,
        "从万丈高空垂落，斜穿整个中洲，东流出中洲入东海",
      },
      {
        "落天河源头内陆海洋", "内陆海／湖泊", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.3400, 0.4400, true,
        "“亿万顷”",
        "被方源取走六成落河水量，水面下降数百丈",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "落天河源头，由薄青冲关形成的坠落水潭扩张而成",
      },
      {
        "罐河", "河", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.6200, 0.5200, true,
        "原文未明",
        "风云府辖下资源点；整条河连同河道被方源搬入至尊仙窍",
        CanonPlace::Status::Absorbed,
        CanonPlace::Evidence::A,
        "中洲东部，宛若玉带雕缀于地表",
      },
      {
        "灵浒泉", "泉／资源点", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.5031, 0.4208, false,
        "原文未明",
        "被方源收取、搬入至尊仙窍",
        CanonPlace::Status::Absorbed,
        CanonPlace::Evidence::A,
        "方源收取罐河后紧接着处理的资源点，具体位置原文未明",
      },
      {
        "玄玉蛇窟", "洞窟／资源点", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.5094, 0.4042, false,
        "“洞窟万千”，具体占地原文未明",
        "被方源收取并搬入至尊仙窍",
        CanonPlace::Status::Absorbed,
        CanonPlace::Evidence::A,
        "中洲著名超级资源点，隶属天妒楼；洞窟层叠，含宇道嵌套空间",
      },
      {
        "藏龙窟", "洞窟／凶地", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.5156, 0.4125, false,
        "原文未明",
        "曾禁锢传奇太古荒兽帝藏生；方源将其搬入至尊仙窍",
        CanonPlace::Status::Absorbed,
        CanonPlace::Evidence::A,
        "中洲内部，具体坐标原文未明",
      },
      {
        "湖心山（洞天内）", "山／灵缘斋大本营", "中洲地表入口附近；山体本身在灵缘斋福地内部", Domain::ZhongZhou,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "含秘传峰、小寒峰、含情峰、凶焰峰、天花峰等，具体面积原文未明",
        "仙子命牌与核心仙蛊已带走，山及建筑被方源搬入至尊仙窍",
        CanonPlace::Status::Absorbed,
        CanonPlace::Evidence::A,
        "中洲，具体入口坐标原文未明",
      },
      {
        "山龟谷", "山谷／资源点", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.5031, 0.4042, false,
        "原文未明",
        "被方源搜刮并搬入至尊仙窍",
        CanonPlace::Status::Absorbed,
        CanonPlace::Evidence::A,
        "湖心山之后被方源处理的地点之一，具体位置原文未明",
      },
      {
        "囚谷", "山谷／资源点", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.5156, 0.4208, false,
        "原文未明",
        "被方源收取",
        CanonPlace::Status::Absorbed,
        CanonPlace::Evidence::A,
        "中洲，具体位置原文未明",
      },
      {
        "红河滩地", "滩地／资源点", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.4969, 0.4125, false,
        "原文未明",
        "被方源收取",
        CanonPlace::Status::Absorbed,
        CanonPlace::Evidence::A,
        "中洲，具体位置原文未明",
      },
      {
        "百节林地", "森林／资源点", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.5094, 0.4292, false,
        "原文未明",
        "被方源收取",
        CanonPlace::Status::Absorbed,
        CanonPlace::Evidence::A,
        "中洲，具体位置原文未明",
      },
      {
        "磷光河", "河／资源点", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.4969, 0.4208, false,
        "原文未明",
        "被方源收取",
        CanonPlace::Status::Absorbed,
        CanonPlace::Evidence::A,
        "中洲，具体位置原文未明",
      },
      {
        "地气石林", "石林／资源点", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.5031, 0.4292, false,
        "原文未明",
        "被方源收取",
        CanonPlace::Status::Absorbed,
        CanonPlace::Evidence::A,
        "中洲，具体位置原文未明",
      },
      {
        "静雨谷", "山谷／资源点", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.5156, 0.4042, false,
        "原文未明",
        "被方源收取",
        CanonPlace::Status::Absorbed,
        CanonPlace::Evidence::A,
        "中洲，具体位置原文未明",
      },
      {
        "灵缘斋大本营", "门派山门／福地", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.4969, 0.4042, false,
        "多座山峰及修行设施；面积原文未明",
        "撤离后建筑大体完好，随后被方源整体迁入仙窍",
        CanonPlace::Status::Absorbed,
        CanonPlace::Evidence::A,
        "湖心山福地，具体地表入口坐标原文未明",
      },
      {
        "天莲派大本营", "门派山门／福地", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.5156, 0.4292, false,
        "原文未明",
        "星宿预先撤离，方源抵达时无人",
        CanonPlace::Status::Declined,
        CanonPlace::Evidence::A,
        "中洲，具体方位原文未明",
      },
      {
        "灵蝶谷大本营", "门派山门／福地", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.4969, 0.4292, false,
        "原文未明",
        "大本营空无一人",
        CanonPlace::Status::Declined,
        CanonPlace::Evidence::A,
        "中洲，具体方位原文未明",
      },
      {
        "古魂门大本营", "门派山门／福地", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.5094, 0.3958, false,
        "原文未明",
        "已撤离；杨峰等人员转驻天庭",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "中洲，具体方位原文未明",
      },
      {
        "天妒楼大本营", "门派山门／福地", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.5219, 0.4125, false,
        "原文未明",
        "空置；玄玉蛇窟等名下资源点被方源收取",
        CanonPlace::Status::Absorbed,
        CanonPlace::Evidence::A,
        "中洲，具体方位原文未明",
      },
      {
        "风云府大本营", "门派山门／福地", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.5031, 0.3958, false,
        "原文未明",
        "大本营空置",
        CanonPlace::Status::Declined,
        CanonPlace::Evidence::A,
        "中洲，具体方位原文未明",
      },
      {
        "战仙宗大本营", "门派山门／福地", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.5219, 0.4208, false,
        "原文未明",
        "大本营空置",
        CanonPlace::Status::Declined,
        CanonPlace::Evidence::A,
        "中洲，具体方位原文未明",
      },
      {
        "黑天寺大本营", "门派山门／福地", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::TwoHeavens,
        -1.0, -1.0, false,
        "原文未明",
        "大本营空置",
        CanonPlace::Status::Declined,
        CanonPlace::Evidence::A,
        "中洲，具体方位原文未明",
      },
      {
        "万龙坞大本营", "门派山门／福地", "中洲", Domain::ZhongZhou,
        CanonPlace::Kind::Surface,
        0.4906, 0.4125, false,
        "龙湖与中心海岛尚在；福地面积原文未明",
        "公共福地仍存但已无人；龙湖、海岛未被写明搬走",
        CanonPlace::Status::Declined,
        CanonPlace::Evidence::A,
        "位于龙湖中心海岛",
      },
      {
        "天庭洞天（洞天内）", "洞天／天下第一势力中枢", "中洲上方的太古白天", Domain::ZhongZhou,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未给面积数字，仅称广阔骇人听闻",
        "星宿仙尊死守，是天庭成员沉眠、复活与最终决战中枢",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "中洲正中高空",
      },
      {
        "监天塔（洞天内）", "仙蛊屋据点", "天庭洞天内", Domain::ZhongZhou,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "第五卷宿命大战中严重受损，仍作为天庭核心依仗；断更时仍在战场",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "天庭洞天中心地带",
      },
      {
        "北原", "草原大陆／域", "北原", Domain::BeiYuan,
        CanonPlace::Kind::Surface,
        0.5406, 0.1042, false,
        "原文未明",
        "王庭福地毁、黑家覆灭、百足家吞并黑家、长生天介入、疯魔窟成为宿命终战战场",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "五域之一，界壁为中洲圣贤界壁北侧的甘草界壁",
      },
      {
        "甘草界壁", "界壁／天然屏障", "北原", Domain::BeiYuan,
        CanonPlace::Kind::Surface,
        0.5406, 0.0958, false,
        "原文未明",
        "与五域其他界壁一样因奥秘解开而逐渐消失",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "北原边缘，与中洲圣贤界壁相接；中洲蛊仙穿过圣贤界壁后即进入甘草界壁",
      },
      {
        "北原草原", "草原", "北原", Domain::BeiYuan,
        CanonPlace::Kind::Surface,
        0.5344, 0.1042, false,
        "原文未明",
        "黑家—东方家大战、王庭之争及后续气潮均影响草原",
        CanonPlace::Status::Battlefield,
        CanonPlace::Evidence::A,
        "北原主体地貌，多平坦、一马平川",
      },
      {
        "月牙湖", "湖", "北原", Domain::BeiYuan,
        CanonPlace::Kind::Surface,
        0.3000, 0.1300, true,
        "“湖长约十五千里，平均宽度五千里”",
        "琅琊福地迁离后坐标变化，月牙湖仍是北原地标",
        CanonPlace::Status::Relocated,
        CanonPlace::Evidence::A,
        "北原草原上；原文称位于琅琊福地迁址前的旧坐标附近",
      },
      {
        "琅琊福地（洞天内）", "福地／炼道势力", "北原月牙湖（旧坐标）", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "迁址后坐标不明；荡魂山、落魄谷均在福地内，福地第六卷时仍存在",
        CanonPlace::Status::Relocated,
        CanonPlace::Evidence::A,
        "初位于北原月牙湖；后整体迁离，新地点只有琅琊帝陵知晓",
      },
      {
        "荡魂山（洞天内）", "山／魂道秘境", "琅琊福地内部", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "在琅琊福地内存续；并非北原地表山峰",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "由狐仙福地迁至琅琊福地",
      },
      {
        "落魄谷（洞天内）", "谷／魂道秘境", "琅琊福地内部", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "与荡魂山同处琅琊福地，是魂修资源点",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "琅琊福地内",
      },
      {
        "琅琊福地云城", "城市／势力据点", "琅琊福地内部", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "琅琊派活动中心；截至断更仍存续",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "琅琊福地内",
      },
      {
        "大雪山", "山／魔道势力", "北原", Domain::BeiYuan,
        CanonPlace::Kind::Surface,
        0.6600, 0.0600, true,
        "原文未明",
        "北原第一魔道势力，大雪山福地由多峰主共管；第六卷前被中洲、天庭介入",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "北原，东方家等黄金部族提及曾共闯大雪山；具体方位原文未明",
      },
      {
        "大雪山福地（洞天内）", "福地", "北原大雪山区域，洞天本体", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "由众蛊仙拼凑的大本营，第六卷前遭围攻，具体存续节点原文未明",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "大雪山；具体入口原文未明",
      },
      {
        "大雪山各支峰", "山峰／势力分支", "北原大雪山", Domain::BeiYuan,
        CanonPlace::Kind::Surface,
        0.5344, 0.0958, false,
        "原文未明",
        "第四至第六峰主曾联合作战",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "至少包括第四、第五、第六支峰",
      },
      {
        "冰湖宫殿", "宫殿／魔道据点", "北原大雪山", Domain::BeiYuan,
        CanonPlace::Kind::Surface,
        0.5469, 0.1042, false,
        "原文未明",
        "第五支峰据点，截至相关章节存续",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "第五支峰，龙胆魔君坐拥",
      },
      {
        "王庭福地（洞天内）", "福地／北原精神象征", "北原，原入口位于地表，福地本体在仙窍内", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "被方源、太白云生升仙与巨阳意志冲突等连续破坏，毁于大同风，形成三千米高空风幕遗址",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "北原核心区域；八十八角真阳楼为其中枢",
      },
      {
        "八十八角真阳楼", "仙蛊屋／福地中枢", "王庭福地内部", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "王庭福地毁灭时未必同步损毁，但地表已不能按原址进入",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "王庭福地第八层顶端",
      },
      {
        "王庭圣宫", "宫殿群／王庭中枢", "王庭福地内部", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "含美妇宫、幼女宫、妩媚殿、纯真殿、异香宫、玉像宫等，总体规模原文未明",
        "巨阳晚年已凋零；福地毁灭后不再可进入",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "王庭福地内",
      },
      {
        "星鹫峰", "山峰／战场", "北原", Domain::BeiYuan,
        CanonPlace::Kind::Surface,
        0.4400, 0.0900, true,
        "原文未明",
        "黑家、常山阴一方争夺/冲突地点，截至王庭福地战存续",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "黑家王庭之争相关区域，具体位置原文未明",
      },
      {
        "龙象原", "草原／战场", "北原", Domain::BeiYuan,
        CanonPlace::Kind::Surface,
        0.3300, 0.1600, true,
        "原文未明",
        "黑家大战及后续追杀涉及区域",
        CanonPlace::Status::Battlefield,
        CanonPlace::Evidence::A,
        "北原，方远离月牙湖后经过的草原区域",
      },
      {
        "黑家王帐", "部族营地／权力中心", "北原", Domain::BeiYuan,
        CanonPlace::Kind::Surface,
        0.4800, 0.1200, true,
        "原文未明",
        "黑家覆灭后营地体系解体，黄金部族格局重组",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "黑家大军行动时所在草原营地",
      },
      {
        "草府", "城寨／中心要塞", "北原", Domain::BeiYuan,
        CanonPlace::Kind::Surface,
        0.5800, 0.1300, true,
        "原文未明",
        "黑家攻破东方部族五道防线后包围草府；东方家后来仍存续于碧潭福地",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "东方部族防线中心地带",
      },
      {
        "太丘", "丘陵／凶地", "北原", Domain::BeiYuan,
        CanonPlace::Kind::Surface,
        0.3600, 0.1100, true,
        "原文未明",
        "北原十大凶地之一；东方长凡智盗传承争夺战场",
        CanonPlace::Status::Battlefield,
        CanonPlace::Evidence::A,
        "关家东南、刘家西北，黄金部族交界附近",
      },
      {
        "地沟", "沟壑／险地", "北原", Domain::BeiYuan,
        CanonPlace::Kind::Surface,
        0.5406, 0.1125, false,
        "原文未明",
        "僵盟最后领地阴流巨城沉入其中，北原僵盟消亡",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "北原凶险地域，靠近琅琊福地迁址目标区",
      },
      {
        "阴流巨城", "城市／僵盟据点", "北原地沟", Domain::BeiYuan,
        CanonPlace::Kind::Surface,
        0.5469, 0.0958, false,
        "原文未明",
        "沉入地沟后隐匿，北原僵盟消失",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "原北原僵盟分部，后沉入地沟",
      },
      {
        "疯魔窟", "深渊／凶地／秘境", "北原", Domain::BeiYuan,
        CanonPlace::Kind::Surface,
        0.3600, 0.1800, true,
        "原文称入口“圆形如瞳，直径十万丈”",
        "第四至第六卷成为无极魔尊传承与疯魔九虚阵核心，第六卷末是宿命大战最后战场",
        CanonPlace::Status::Battlefield,
        CanonPlace::Evidence::A,
        "北原地表一处巨大洞口，北原十大凶地之一",
      },
      {
        "疯魔窟第一层", "凶地层级／雨林", "疯魔窟内部", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "可进入；被魔音和荒兽生态覆盖",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "疯魔窟最外层",
      },
      {
        "疯魔窟第二层", "凶地层级／火岩石滩", "疯魔窟内部", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "可进入；炙热火岩环境",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "第一层之下",
      },
      {
        "疯魔窟第三层", "凶地层级／雾林", "疯魔窟内部", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "可进入；雾都与猛兽构成险境",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "第二层之下，有雾都",
      },
      {
        "疯魔窟第四层", "凶地层级", "疯魔窟内部", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "疯魔三怪止步第七层，第四至六层曾探索；原文未给统一层名",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::C,
        "第三层之下",
      },
      {
        "疯魔窟第五层", "凶地层级", "疯魔窟内部", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "同第四层；无可靠统一层名",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::C,
        "第四层之下",
      },
      {
        "疯魔窟第六层", "凶地层级", "疯魔窟内部", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "同第四层；无可靠统一层名",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::C,
        "第五层之下",
      },
      {
        "疯魔窟第七层", "凶地层级", "疯魔窟内部", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "方源与疯魔三怪曾止步；逐层探索终点",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "疯魔窟倒数第三层",
      },
      {
        "疯魔窟第八层", "凶地层级／融汇战区", "疯魔窟内部", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "大小世界迅速融汇，成为天庭支持的气运之子与方源阵营交战处",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "第七层之下",
      },
      {
        "疯魔窟第九层", "凶地层级／宿命战场", "疯魔窟内部", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "疯魔九虚阵核心所在；第六卷末星宿、巨阳、方源等争夺事实浮冰，是全书断更前主战场",
        CanonPlace::Status::Battlefield,
        CanonPlace::Evidence::A,
        "疯魔窟最深处",
      },
      {
        "事实浮冰", "秘境核心／战利品", "疯魔窟第九层", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "被双尊、方源等争夺；方源已夺得至少占总量的约一成",
        CanonPlace::Status::Absorbed,
        CanonPlace::Evidence::A,
        "第九层内",
      },
      {
        "元境", "智道秘境", "疯魔窟第九层", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文称“球形洁白光影”，未给面积",
        "被无极魔尊安置于第九层，参与疯魔九虚阵",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "第九层核心区域之一",
      },
      {
        "书山", "律道秘境", "疯魔窟第九层", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "无极魔尊安置于第九层，记录流派知识并推动阵法演进",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "第九层核心区域之一",
      },
      {
        "碧潭福地（洞天内）", "福地／东方家大本营", "北原", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "东方家存续基地；第六卷前遭围攻后仍有活动",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "由众多东方家蛊仙割舍福地拼凑而成，种于地表以汲取地气",
      },
      {
        "铁鹰福地（洞天内）", "福地／黑家大本营", "北原", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "黑家覆灭后失去超级势力地位；断更时是否完整存续原文未明",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::B,
        "黑家领地上方/地表福地",
      },
      {
        "阴阳福地（洞天内）", "福地／慕容家大本营", "北原", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "黄金家族格局延续，截至断更未写明毁灭",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::B,
        "慕容家领地，东方家称其盛景胜过碧潭福地",
      },
      {
        "十荒福地（洞天内）", "福地／关家大本营", "北原", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "关家仍为超级黄金部族，截至断更存续",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::B,
        "关家领地，邻近太丘",
      },
      {
        "玄龟福地（洞天内）", "福地／刘家大本营", "北原", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "接收长生令并介入百足家事务；截至断更存续",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "刘家领地，邻近太丘、关家",
      },
      {
        "百足洞天（洞天内）", "洞天／百足家", "北原高空", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "百足家吞并黑家，成为长生天下令制衡的对象",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "百足天君仙窍，北原黑凡相关事务发生地",
      },
      {
        "黑凡洞天（洞天内）", "洞天", "北原", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "楚度、方源先后介入；断更前是北原争夺焦点之一",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "北原高空，楚度曾成为洞天之主",
      },
      {
        "药皇洞天（洞天内）", "洞天", "北原", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "题干所列北原洞天之一；截至断更存续",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::B,
        "北原，具体坐标原文未明",
      },
      {
        "凤仙洞天（洞天内）", "洞天", "北原", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "北原洞天之一；未给末节详细战况",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::B,
        "北原，宫家凤仙太子常住",
      },
      {
        "黑家领地", "家族领地／草原", "北原", Domain::BeiYuan,
        CanonPlace::Kind::Surface,
        0.4700, 0.1000, true,
        "原文未明",
        "黑家覆灭，领地权力真空并被百足家等觊觎",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "北原王庭之争核心草原，包含王帐、防线与太丘方向",
      },
      {
        "东方家领地", "家族领地／草原防线", "北原", Domain::BeiYuan,
        CanonPlace::Kind::Surface,
        0.5600, 0.1200, true,
        "原文未明",
        "遭黑家攻破，但家族通过碧潭福地延续",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "含草府与五道防线，邻近太丘方向",
      },
      {
        "刘家领地", "家族领地", "北原", Domain::BeiYuan,
        CanonPlace::Kind::Surface,
        0.3900, 0.1300, true,
        "原文未明",
        "接收长生令；参与黄金部族联盟事务",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "太丘西北、关家附近",
      },
      {
        "关家领地", "家族领地", "北原", Domain::BeiYuan,
        CanonPlace::Kind::Surface,
        0.3300, 0.0900, true,
        "原文未明",
        "十荒福地所在；与太丘事件直接相关",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "太丘东南、刘家西北",
      },
      {
        "慕容家领地", "家族领地", "北原", Domain::BeiYuan,
        CanonPlace::Kind::Surface,
        0.6200, 0.1000, true,
        "原文未明",
        "阴阳福地所在；关注长生天对百足家态度",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "北原，具体方位原文未明",
      },
      {
        "耶律家领地", "家族领地", "北原", Domain::BeiYuan,
        CanonPlace::Kind::Surface,
        0.5344, 0.1125, false,
        "原文未明",
        "黄金家族之一，曾被方源得罪但随后偃旗息鼓",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::B,
        "北原，具体方位原文未明",
      },
      {
        "廿二家领地", "家族领地", "北原", Domain::BeiYuan,
        CanonPlace::Kind::Surface,
        0.5406, 0.0875, false,
        "原文未明",
        "黄金血脉部族群体；受长生天长生令影响",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::B,
        "北原，具体分布原文未明",
      },
      {
        "冰塞川活动地域", "草原／战场", "北原", Domain::BeiYuan,
        CanonPlace::Kind::Surface,
        0.5281, 0.1042, false,
        "原文未明",
        "冰塞川作为长生天西荒仙人苏醒，指挥劫运坛参与疯魔窟大战",
        CanonPlace::Status::Battlefield,
        CanonPlace::Evidence::A,
        "北原及疯魔窟战场",
      },
      {
        "长生天（洞天内）", "洞天／北原最高势力中枢", "北原上空白天天域", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "由巨阳仙尊九转洞天形成，四荒八极体系仍运转；第六卷末派众进入疯魔窟参战",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "北原之上，北原最高统治层级",
      },
      {
        "劫运坛", "仙蛊屋／长生天据点", "长生天内部／疯魔窟战场", Domain::BeiYuan,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "冰塞川率长生天众仙驾驶，参与疯魔窟大战",
        CanonPlace::Status::Battlefield,
        CanonPlace::Evidence::A,
        "平时在长生天，战时进入疯魔窟倒数第二层及战场",
      },
      {
        "龙鱼海域", "海域", "东海（五域地表）", Domain::DongHai,
        CanonPlace::Kind::Surface,
        0.7700, 0.4200, true,
        "原文未明",
        "存续；方源曾借武家渠道向正道销售龙鱼，其身份暴露后贸易渠道断绝，但该海域本身未被正文写明确认易主或毁弃。",
        CanonPlace::Status::ChangedOwner,
        CanonPlace::Evidence::A,
        "东海海面，具体方位原文未明",
      },
      {
        "乱流海域", "海域", "东海（五域地表）", Domain::DongHai,
        CanonPlace::Kind::Surface,
        0.8900, 0.5600, true,
        "原文未明",
        "存续；仅有名称与东海海域划分信息，第368节前未见明确灾变记录。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "东海海面，具体方位原文未明",
      },
      {
        "射鱼海域", "海域", "东海（五域地表）", Domain::DongHai,
        CanonPlace::Kind::Surface,
        0.8300, 0.5000, true,
        "原文未明",
        "存续；具体势力归属与规模原文未明。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "东海海面，具体方位原文未明",
      },
      {
        "光波海域", "海域", "东海（五域地表）", Domain::DongHai,
        CanonPlace::Kind::Surface,
        0.9300, 0.3800, true,
        "原文未明",
        "存续；具体资源与势力归属原文未明。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "东海海面，具体方位原文未明",
      },
      {
        "绿波海域", "海域", "东海（五域地表）", Domain::DongHai,
        CanonPlace::Kind::Surface,
        0.8000, 0.3000, true,
        "原文未明",
        "存续；与仙蛊屋“绿波亭”同名关系虽可合理联想，但正文未明确同址，本表不作合并认定。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "东海海面，具体方位原文未明",
      },
      {
        "鲨海海域", "海域", "东海（五域地表）", Domain::DongHai,
        CanonPlace::Kind::Surface,
        0.8600, 0.6600, true,
        "原文未明",
        "存续；鲨魔掌控该海域，属东海海域排名体系中的个人势力范围。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "东海海面，具体方位原文未明",
      },
      {
        "锦绣海域", "海域", "东海（五域地表）", Domain::DongHai,
        CanonPlace::Kind::Surface,
        0.9500, 0.5200, true,
        "原文未明",
        "存续；具体资源与势力归属原文未明。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "东海海面，具体方位原文未明",
      },
      {
        "颠簸海域", "海域", "东海（五域地表）", Domain::DongHai,
        CanonPlace::Kind::Surface,
        0.7900, 0.6200, true,
        "原文未明",
        "存续；具体资源与势力归属原文未明。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "东海海面，具体方位原文未明",
      },
      {
        "诗情海域", "海域", "东海（五域地表）", Domain::DongHai,
        CanonPlace::Kind::Surface,
        0.9100, 0.4400, true,
        "原文未明",
        "存续；方源曾潜入行宫附近，未写夺取海域。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "东海海面，宋亦诗私人海域；邻近海底火山行宫，具体大方位原文未明",
      },
      {
        "龙鳞海域（洞天内）", "海域", "至尊仙窍（方源仙窍内部）", Domain::DongHai,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "至尊仙窍内第一大海域；正文未给具体面积",
        "存续并持续经营；方源宙道分身曾巡视，海域波涛由仙阵制造，金鳞龙鱼已培育到上古荒兽层次。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "至尊仙窍中的“小东海”",
      },
      {
        "鲛人海域", "海域", "东海（五域地表）", Domain::DongHai,
        CanonPlace::Kind::Surface,
        0.7600, 0.6800, true,
        "原文未明",
        "存续；鲛人王庭作为超级势力活动，受乐土仙尊旧有影响而得到东海人族势力承认。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "东海海底；鲛人族集中分布区，与陆上人族八大家族体系相区别",
      },
      {
        "鲛人王庭", "异人势力／海底据点", "东海（五域地表）", Domain::DongHai,
        CanonPlace::Kind::Surface,
        0.7400, 0.7000, true,
        "原文未明",
        "存续；最顶尖三位太上大长老仅七转，长期以联姻、招婿及依附强权求存；至尊节点未见王庭覆灭。",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "鲛人海域内，具体经纬度原文未明",
      },
      {
        "苍蓝龙鲸", "传奇太古荒兽／仙窍载体", "东海（五域地表）", Domain::DongHai,
        CanonPlace::Kind::Surface,
        0.8800, 0.3400, true,
        "原文未明",
        "存续；其体内仙窍已化为龙鲸洞天，并非普通鲸体空腔。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "东海海面活动，具体迁徙路线原文未明",
      },
      {
        "龙鲸乐土（洞天内）", "洞天", "苍蓝龙鲸体内（仙窍内部）", Domain::DongHai,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "存续并被乐土仙尊改造；内有功德方尖碑、悔蛊相关设施及异族共存秩序。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "位于苍蓝龙鲸体内，外部表现随荒兽迁徙而移动",
      },
      {
        "海底潜流", "潜流", "东海（五域地表）", Domain::DongHai,
        CanonPlace::Kind::Surface,
        0.8656, 0.5542, false,
        "多股纵横盘踞；正文称借流可跨越数万里乃至数十万里，未给总长度",
        "存续；是深海商队的重要天然交通网络，方源侦查用蛊曾沿其快速移动。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "横贯东海海底，可连接海底悬崖、海底火山等节点；非单一固定河段",
      },
      {
        "东海苍水界壁", "界壁", "东海与域外之间（五域地表边界）", Domain::DongHai,
        CanonPlace::Kind::Surface,
        0.8656, 0.5625, false,
        "原文未明",
        "存续；对高阶生命阻碍更强，东海僵盟曾造人工地潮令局部薄弱。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "环绕东海，与北原等外域相邻；具体穿行点原文未明",
      },
      {
        "东海八大家族各海域领地", "家族领地", "东海（五域地表）", Domain::DongHai,
        CanonPlace::Kind::Surface,
        0.8719, 0.5542, false,
        "原文未明",
        "总体存续；第368节前正道家族仍出席方源主持的东海场合，未写八家整体覆灭或一统。",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "分布于东海诸海域；青岳、宋、华、夏、蔡、苏、南宫、解诸家具体海域名称与边界原文未明",
      },
      {
        "东海僵盟总部", "海底势力据点", "东海（五域地表）", Domain::DongHai,
        CanonPlace::Kind::Surface,
        0.8200, 0.7400, true,
        "原文未明",
        "存续；可组织数十位仙僵共同催发蛊阵，制造人工地潮以辅助穿界。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "东海海底，具体海域原文未明",
      },
      {
        "华文洞天", "洞天", "白天（东海上方）", Domain::DongHai,
        CanonPlace::Kind::TwoHeavens,
        -1.0, -1.0, false,
        "原文未明",
        "存续；由八转信道蛊仙仙窍所化，华语老仙执掌；碎骨洞天联络人视其为白天一方重要争取对象。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "东海之上的白天深处，具体坐标原文未明",
      },
      {
        "碎骨洞天", "洞天", "黑天（东海上方）", Domain::DongHai,
        CanonPlace::Kind::TwoHeavens,
        -1.0, -1.0, false,
        "原文未明",
        "存续；由骷髅姥姥执掌，并参与黑天人族洞天联合动向。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "东海之上的太古黑天，具体坐标原文未明",
      },
      {
        "弯月洞天", "洞天", "黑天（东海上方）", Domain::DongHai,
        CanonPlace::Kind::TwoHeavens,
        -1.0, -1.0, false,
        "原文未明",
        "存续；由弯月仙子执掌，月道特征明显；本清单不采用后续章节对其归属与命运的补充。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::B,
        "东海之上的太古黑天，具体坐标原文未明",
      },
      {
        "怎渡丘", "流动沙丘／天然奇观", "西漠（五域地表）", Domain::XiMo,
        CanonPlace::Kind::Surface,
        0.1400, 0.5000, true,
        "沙丘群绵延数十万里，为七大天然奇观之一",
        "存续且持续迁徙；轨迹固定，内层中心难以探索，萧家蛊仙曾在曲线外围与潜沙蛛后作战。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "迁徙曲线横贯大半西漠，具体起止点原文未明",
      },
      {
        "青鬼沙漠", "沙漠", "西漠（五域地表）", Domain::XiMo,
        CanonPlace::Kind::Surface,
        0.1000, 0.4200, true,
        "原文未明",
        "存续；房家拟开拓，方源屠戮燎萤戈壁以牵制其开发进度，但青鬼沙漠本体未被写明确认易主。",
        CanonPlace::Status::ChangedOwner,
        CanonPlace::Evidence::A,
        "西漠内部，与天露绿洲、燎萤戈壁开发线相关；具体方位原文未明",
      },
      {
        "震荡沙漠", "沙漠", "西漠（五域地表）", Domain::XiMo,
        CanonPlace::Kind::Surface,
        0.0900, 0.5800, true,
        "原文未明",
        "存续；具体战事与归属原文未明。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "西漠内部，具体方位原文未明",
      },
      {
        "风隼沙漠", "沙漠", "西漠（五域地表）", Domain::XiMo,
        CanonPlace::Kind::Surface,
        0.1600, 0.5800, true,
        "原文未明",
        "存续；万家镇守高松绿洲，风隼与房家进攻线直接相关，但未写沙漠整体失守。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "西漠内部，高松绿洲风隼族群活动区；具体方位原文未明",
      },
      {
        "万矿戈壁", "戈壁／矿脉区", "西漠（五域地表）", Domain::XiMo,
        CanonPlace::Kind::Surface,
        0.2000, 0.3200, true,
        "矿场、矿脉及地下空间范围广；有明确“上十万石人矿工”",
        "存续并由石家掌控；地下存在太古黄天遗脉相关的髓金河流及仙道蛊阵。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "西漠内部，石家掌控区；具体方位原文未明",
      },
      {
        "燎萤戈壁", "戈壁", "西漠（五域地表）", Domain::XiMo,
        CanonPlace::Kind::Surface,
        0.1200, 0.3600, true,
        "原文未明",
        "被方源屠戮，形成房家对正道赔偿压力；是否彻底荒废、是否仍属房家控制，正文未明。",
        CanonPlace::Status::Absorbed,
        CanonPlace::Evidence::A,
        "西漠内部，与青鬼沙漠开发线相邻；具体方位原文未明",
      },
      {
        "天露绿洲", "绿洲", "西漠（五域地表）", Domain::XiMo,
        CanonPlace::Kind::Surface,
        0.1050, 0.6200, true,
        "原文未明",
        "房家体系存续；方源曾坐镇此地修行，且以房家谈判筹码迫使对方付出天露。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "西漠内部，房家相关资源点；具体方位原文未明",
      },
      {
        "宝月绿洲", "绿洲", "西漠（五域地表）", Domain::XiMo,
        CanonPlace::Kind::Surface,
        0.1600, 0.4400, true,
        "原文未明",
        "存续；具体归属与战事原文未明。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "西漠内部，具体方位原文未明",
      },
      {
        "高松绿洲", "绿洲", "西漠（五域地表）", Domain::XiMo,
        CanonPlace::Kind::Surface,
        0.2400, 0.5800, true,
        "原文未明",
        "存续但遭房家进攻；正文中万家强调其不可有失，未写被攻破。",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "西漠内部，万家核心资源点；与风隼沙漠相邻",
      },
      {
        "观想绿洲", "绿洲", "西漠（五域地表）", Domain::XiMo,
        CanonPlace::Kind::Surface,
        0.1700, 0.5400, true,
        "原文未明",
        "万家拟割让给萧家，作为针对房家的联盟交换条件；截至节点不能确认已完成交割。",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "西漠内部，万家资源点；具体方位原文未明",
      },
      {
        "香风飞岛", "飞岛／资源点", "西漠（五域地表）", Domain::XiMo,
        CanonPlace::Kind::Surface,
        0.1500, 0.4800, true,
        "原文未明",
        "万家拟割让给萧家，作为联盟交换条件；截至节点不能确认已完成交割。",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "西漠内部，万家资源点；具体方位原文未明",
      },
      {
        "玄黄地池", "地池／资源点", "西漠（五域地表）", Domain::XiMo,
        CanonPlace::Kind::Surface,
        0.1900, 0.6400, true,
        "原文未明",
        "万家拟割让给萧家，作为联盟交换条件；截至节点不能确认已完成交割。",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "西漠内部，万家资源点；具体方位原文未明",
      },
      {
        "西漠狂炎界壁", "界壁", "西漠与域外之间（五域地表边界）", Domain::XiMo,
        CanonPlace::Kind::Surface,
        0.1281, 0.4708, false,
        "原文未明",
        "存续；对高阶生命阻碍更强，是五域互迁的常规障碍。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "环绕西漠，与其他四域相接；具体穿行点原文未明",
      },
      {
        "西漠十四家族领地", "家族领地", "西漠（五域地表）", Domain::XiMo,
        CanonPlace::Kind::Surface,
        0.1281, 0.4625, false,
        "原文未明",
        "总体存续但出现房家主动打破平衡；不能因“十四家族”之名推断截至节点仍彼此完全对等。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "分布于西漠绿洲、沙漠与戈壁；房、万、左丘、萧、田、董、唐、秦、孙、莫、石、龚、林、拓跋各家具体边界原文未明",
      },
      {
        "房家大本营福地", "福地", "西漠（五域地表，仙窍落于西漠）", Domain::XiMo,
        CanonPlace::Kind::Surface,
        0.1344, 0.4708, false,
        "原文未明",
        "存续；万家联盟曾到访并结盟，是房家西漠布局的根据地。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "西漠内部，具体位置原文未明",
      },
      {
        "萧家大本营福地", "福地", "西漠（五域地表，仙窍落于西漠）", Domain::XiMo,
        CanonPlace::Kind::Surface,
        0.1344, 0.4625, false,
        "原文未明",
        "存续；万家、孙家等曾至此结成反房联盟。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "西漠内部，具体位置原文未明",
      },
      {
        "董家福地", "福地", "西漠（五域地表，仙窍落于西漠）", Domain::XiMo,
        CanonPlace::Kind::Surface,
        0.1219, 0.4708, false,
        "原文未明",
        "存续；羽化天坑位于其中，因防守相对薄弱而遭房家设伏，但福地本体未被写明确认失陷。",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "西漠内部，羽化天坑所在福地；具体位置原文未明",
      },
      {
        "羽化天坑", "天坑／资源点", "董家福地（仙窍内部）", Domain::XiMo,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "遭房家攻入，仙阵被破、资源遭搜刮，讨房联盟反被诱入仙阵；天坑此后归属原文未明。",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "位于董家福地内部；由房家进攻路线推知接近董家地盘边线",
      },
      {
        "骨架山", "山／资源点", "西漠（五域地表）", Domain::XiMo,
        CanonPlace::Kind::Surface,
        0.1300, 0.3000, true,
        "原文未明",
        "被房家攻取后彻底消失，习家镇守蛊仙失踪；原文没有“迁址”或“重建”记录。",
        CanonPlace::Status::Relocated,
        CanonPlace::Evidence::A,
        "习家领地边线，具体坐标原文未明",
      },
      {
        "龙吟火山", "火山／资源点", "西漠（五域地表）", Domain::XiMo,
        CanonPlace::Kind::Surface,
        0.1700, 0.6800, true,
        "原文未明",
        "被房家攻取，地表火山及地下岩浆被抽走，成为其展示提升后攻伐能力的标志。",
        CanonPlace::Status::ChangedOwner,
        CanonPlace::Evidence::A,
        "董家领地边线，距离羽化天坑路线可推算较近；具体坐标原文未明",
      },
      {
        "上清草原", "草原／资源点", "西漠（五域地表）", Domain::XiMo,
        CanonPlace::Kind::Surface,
        0.2000, 0.7200, true,
        "原文未明",
        "被房家攻陷；正文明言其水草丰美、产水道与木道资源，但未交代战后归属。",
        CanonPlace::Status::ChangedOwner,
        CanonPlace::Evidence::A,
        "西漠中罕见草原，距龙吟火山最近；具体坐标原文未明",
      },
      {
        "隐世羿家领地", "隐世家族领地", "西漠（五域地表）", Domain::XiMo,
        CanonPlace::Kind::Surface,
        0.1281, 0.4792, false,
        "原文未明",
        "本清单不采用2026年以后网络转述；截至第368节可保留为“有羽民血统线索、原文坐标未核”，不能据此补写地望。",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::C,
        "西漠内部，具体位置原文未明",
      },
      {
        "十万大山", "山/森林", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4594, 0.8542, false,
        "原文称“十万大山”，未给具体面积数字",
        "仍是南疆地表主体地貌；第六卷时南疆家族势力围绕三江、山寨持续整合与冲突，地貌本体未见整体改变",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "南疆主体地貌，由黄龙江走向可知其位于黄果山以东、玄冥山—龟背山—青茅山—白骨山—雷磁山等群山之间",
      },
      {
        "青茅山", "山", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4300, 0.7800, true,
        "原文未明；仅明确古月山寨占据“一隅”，山体大于山寨",
        "山寨体系已毁，但山体仍是方源等人物活动与返场的坐标；第六卷末未见山体整体消亡",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "黄龙江沿岸，发源黄果山后流经玄冥山、龟背山，继而经青茅山、白骨山、雷磁山",
      },
      {
        "古月山寨", "山寨", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4531, 0.8542, false,
        "山腰聚居区，高脚吊楼“数千”规模；非全山",
        "狼潮、兽潮与袭击后衰败；方源重返时山寨已破败、废墟化，且方源曾在附近捕杀古月族人；至断更节点仍无复兴证据",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "青茅山山腰，熊家寨在前山、白家寨在后山瀑布；山寨附近村庄受其统治",
      },
      {
        "熊家寨", "山寨", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4594, 0.8625, false,
        "原文未明",
        "早期即与古月、白家并列为青茅山三大山寨；第六卷时作为青茅山旧势力格局的一部分，未见存续复兴",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::B,
        "青茅山前山",
      },
      {
        "白家寨", "山寨", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4531, 0.8625, false,
        "原文未明",
        "与熊家寨同为早期三大山寨之一；后期青茅山整体失序，至第368节未见复兴",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::B,
        "青茅山后山瀑布",
      },
      {
        "家主阁", "建筑/权力中枢", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4594, 0.8458, false,
        "五层；阁前为广场",
        "山寨衰败后失去统治功能；具体是否残存无正文描述",
        CanonPlace::Status::Declined,
        CanonPlace::Evidence::A,
        "古月山寨正中央",
      },
      {
        "学堂", "机构/建筑", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4531, 0.8458, false,
        "原文未明",
        "随古月山寨一同失去正常教学功能；断更前未述其存续",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "古月山寨内",
      },
      {
        "地下溶洞灵泉", "溶洞/矿脉式资源点", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4656, 0.8542, false,
        "溶洞内有宽三丈余的地下河；灵泉产“大量元石”但无面积数字",
        "古月一族根基；山寨被毁后是否仍由古月残部控制原文未明，不宜写作已易主",
        CanonPlace::Status::ChangedOwner,
        CanonPlace::Evidence::A,
        "家主阁一层大堂入口向下，石梯深入地下溶洞",
      },
      {
        "月兰花海", "花海/培养基地", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4469, 0.8542, false,
        "原文称“这片花海”，面积未明",
        "古月一族重要蛊虫食材培养基地；山寨衰败后状况原文未明",
        CanonPlace::Status::Declined,
        CanonPlace::Evidence::A,
        "地下溶洞灵泉地下河对岸",
      },
      {
        "百足山", "山", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4400, 0.8000, true,
        "原文未明",
        "黄龙江章节列名，属方源早年漂流所经山系；第六卷末状态原文未明",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "黄龙江流经的山系之一；由“黄龙江”章节可知其位于青茅山—白骨山—雷磁山序列",
      },
      {
        "商量山", "山", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4700, 0.7200, true,
        "商家城“几乎覆盖整个商量山”，但山体面积未给数字",
        "商家城作为南疆贸易中心持续经营；第六卷时未见山体或主城毁灭",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "商家城所在山体；位于南疆内陆贸易通道，具体经纬度原文未给",
      },
      {
        "商家城", "城市", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4700, 0.7200, true,
        "外城面积“南疆第一”；上万家商铺、数十万人；内城立体，街道可十辆马车并排",
        "存续且仍是南疆贸易枢纽；第六卷末未见被方源吞并或毁灭",
        CanonPlace::Status::Absorbed,
        CanonPlace::Evidence::A,
        "几乎覆盖整个商量山；外城依山而建，内城深入山体",
      },
      {
        "青阳山", "山", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4000, 0.9000, true,
        "原文未明",
        "乔家作为武家姻亲与西线势力仍据有；第六卷时未述失守",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "乔家大本营所在山；位于武家光芒笼罩的南疆体系中，具体经邻山未明",
      },
      {
        "万程山", "山", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.5000, 0.8800, true,
        "原文未明",
        "铁家寨及镇魔塔存续；铁若男回归后铁家仍为一等势力",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "铁家山寨所在山；属南疆正道势力范围",
      },
      {
        "铁家寨", "山寨", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.5000, 0.8800, true,
        "原文未明",
        "存续；为南疆正道巨头，未在第368节前被方源攻破",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "万程山上，镇魔塔矗立于山巅",
      },
      {
        "铁家十三堂", "擂台/考核机构", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4656, 0.8625, false,
        "原文未明",
        "铁若男回归后闯堂并任少主，机构正常运作",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "铁家寨内部",
      },
      {
        "镇魔塔", "塔/监狱", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4469, 0.8625, false,
        "高百丈，近百层",
        "存续，继续关押魔道蛊师；是铁家与正道象征，断更前未被毁",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "万程山山巅最高处",
      },
      {
        "万蛇山", "山", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.3400, 0.8600, true,
        "原文未明",
        "池家据有并参与南疆西线博弈；第六卷末未述易主或被吞并",
        CanonPlace::Status::ChangedOwner,
        CanonPlace::Evidence::A,
        "池家大本营所在山；位于南疆最西部",
      },
      {
        "池家", "家族领地", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.3500, 0.8700, true,
        "原文未明",
        "存续，并收到方源联合攻羊家的信；未在第368节前被灭",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "南疆最西部；右下方为羊家，右侧为乔家",
      },
      {
        "乔家", "家族领地", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4000, 0.9000, true,
        "原文未明",
        "武家姻亲与西线势力；第六卷时仍据青阳山",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "南疆西部中心地带，北抗巴家、夏家，西对池家，西南牵制羊家",
      },
      {
        "玄冥山", "山", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.3700, 0.7600, true,
        "原文未明",
        "属黄龙江沿线旧山名；第六卷末状态原文未明",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "黄龙江上游，黄果山之后、龟背山之前",
      },
      {
        "龟背山", "山", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4000, 0.7900, true,
        "原文未明",
        "仅列于黄龙江流向；第六卷末状态原文未明",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "黄龙江自玄冥山向东南流后经过",
      },
      {
        "白骨山", "山", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4600, 0.8200, true,
        "原文未明",
        "百家前世迁居并开发白骨传承；第六卷末是否仍为百家领地原文未明，不臆定",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "黄龙江自青茅山之后流经之处，列于青茅山、雷磁山之间",
      },
      {
        "雷磁山", "山", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4900, 0.8500, true,
        "原文未明",
        "仅列于黄龙江流向；第六卷末状态原文未明",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "黄龙江流经白骨山后的下一列山",
      },
      {
        "黄果山", "山", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.3300, 0.7200, true,
        "原文未明",
        "仍是黄龙江源头坐标；第六卷末状态原文未明",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "黄龙江发源地",
      },
      {
        "武家领地", "家族领地", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4400, 0.9500, true,
        "原文未明；仅知为超级势力，规模“广”但无数字",
        "武独秀死后武庸继任，武家正道魁首地位受冲击但仍存续；第六卷末未述覆灭",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "南疆西南区域，南疆最南的超级势力；赤龙江沿途地盘与其接壤",
      },
      {
        "翼家", "家族领地", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.6000, 0.7400, true,
        "原文未明",
        "存续，并与武家保持远交关系；第六卷末未述易主",
        CanonPlace::Status::ChangedOwner,
        CanonPlace::Evidence::A,
        "大本营鳞翅山，位于南疆东北角，最靠近东海",
      },
      {
        "侯家", "家族领地", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4594, 0.8708, false,
        "原文未明",
        "作为正道家族存续；第六卷末无明确覆灭记载",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::B,
        "南疆正道十三家族之一，具体山体与邻山原文未明",
      },
      {
        "羊家", "家族领地", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.3800, 0.9300, true,
        "原文未明",
        "正攻击武家边境、攻破凡人山寨并欲染指诈尸山；截至第368节尚未见被池家吞并",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "池家右下方、武家疆域邻接处；与武家交界处的毒瘟瀑布附近存在冲突",
      },
      {
        "飞家", "家族领地", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4531, 0.8708, false,
        "原文未明",
        "存续；家族成员参与义天山魔道一方，不等于家族山寨被灭",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::B,
        "南疆正道十三家族之一；蓝眉鹤、飞鼬王为南疆飞行大师，但飞家具体山名原文未明",
      },
      {
        "百家", "家族领地", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4656, 0.8458, false,
        "原文未明",
        "“前世”为设定性回忆；第六卷现世时间线中百家是否完成迁居原文未明，不写作已占据",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "白骨山；前世百家迁徙于此并开发五个奶泉眼",
      },
      {
        "巴家", "家族领地", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.5500, 0.8800, true,
        "原文未明",
        "与柴家、夏家并立；第六卷中尚未被武家—柴家联合军吞并",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "赤龙江—碧龙江两江交汇处以“下方”位置出现，具体山体称“大宅山”",
      },
      {
        "柴家", "家族领地", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.5700, 0.8600, true,
        "原文未明",
        "收到方源以武家名义的联攻提议，正与巴家、夏家对峙；第六卷末未覆灭",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "赤龙江—碧龙江两江交汇处，人烟山位于交汇形态上端",
      },
      {
        "夏家", "家族领地", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.5900, 0.8700, true,
        "原文未明",
        "与柴家、巴家并立，受武家—柴家联盟威胁；第368节前未灭",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "两江交汇处以“右方”出现，延寿山为其山体",
      },
      {
        "义天山", "山", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.5600, 0.8200, true,
        "原文未明；能承载正魔双方大规模战斗",
        "第一次被武神通攻击后义天寨受损；陆钻风斩武神通，正道第一波攻势瓦解。第二次武家联合商家蛊仙再攻，义天寨凭蓝眉鹤、飞鼬王一度占上风并将正道逼退。截至第368节，义天山未被记为彻底毁灭，但两场大战后山寨与山体应严重损毁",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "南疆正魔冲突战场之一，具体经纬度原文未给",
      },
      {
        "义天寨", "山寨", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.5600, 0.8200, true,
        "原文未明",
        "两度正魔大战后仍是魔道据点；截至断更节点未明确被荡平",
        CanonPlace::Status::Battlefield,
        CanonPlace::Evidence::A,
        "义天山上",
      },
      {
        "三王山", "山", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.5200, 0.9000, true,
        "原文未明",
        "三王传承争夺后山体现状未持续追述；第368节前未明确毁灭",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::B,
        "三王传承所在山；具体邻山与经纬度原文未明",
      },
      {
        "三王福地", "福地", "洞天/福地内部", Domain::NanJiang,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "已脱离三王山成为可移动的仙窍福地；截至第368节归属随继承者，不作无据推演",
        CanonPlace::Status::Relocated,
        CanonPlace::Evidence::B,
        "原寄托于三王山，后由取得传承者迁入仙窍",
      },
      {
        "白骨山（训练场地）", "其他/试炼地", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4469, 0.8458, false,
        "原文未明",
        "用于白凝冰修炼、布设骨枪相关传承线索；第六卷末状态原文未明",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "原文所称白骨山，与百家相关区域重合但未明确同一坐标",
      },
      {
        "诈尸山", "山/资源地", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4000, 0.9500, true,
        "原文未明",
        "羊家打开毒瘟瀑布缺口后欲夺取，但截至相关章节尚未完成占领；第368节末结果原文未明",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "羊家攻破毒瘟瀑布附近武家凡人山寨后，可“长驱直入”染指之处",
      },
      {
        "毒瘟瀑布", "瀑布/资源点", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4100, 0.9400, true,
        "紫色瀑布，高十八丈",
        "武家凡人山寨被羊家攻破、成废墟；瀑布作为资源点本身未被记为摧毁，但归属冲突未决",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "羊家与武家疆域交界处；附近另有武家布置的凡人山寨",
      },
      {
        "五界山脉", "仿界壁秘境", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.6200, 0.7900, true,
        "原文未明",
        "存续，作为陶铸真传考验地；其五色山体对应五域界壁，非自然山脉",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "南疆某处，为八转蛊仙陶铸刻意打造",
      },
      {
        "铜印山", "山", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.6000, 0.7600, true,
        "原文未明",
        "第368节前状态原文未明",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::B,
        "原文仅列为南疆山川之一，具体邻山与经纬度未给",
      },
      {
        "云竹山", "山", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4700, 0.7000, true,
        "原文未明",
        "第368节前状态原文未明",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::B,
        "原文仅列为南疆山川之一，具体位置未给",
      },
      {
        "尸皇芋顶", "峰/凶地", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.5700, 0.8200, true,
        "尸山高达数百丈",
        "由八转仙僵尸身、江水灵气与水草形成，产僵尸蛊、尸气蛊；僵盟曾高价求购但被武家拒绝。第六卷时仍是武家控制的重要凶地，未见被方源吞并",
        CanonPlace::Status::Absorbed,
        CanonPlace::Evidence::A,
        "赤龙江、黄龙江交汇处，江心漩涡东北岸；姚家蛊仙曾登顶观察",
      },
      {
        "赤龙江", "江", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.5200, 0.8600, true,
        "原文称“几乎贯穿南疆”，无总长度数字",
        "江畔灵气充沛、元泉众多，是超级势力争夺带；第六卷时仍是南疆主要水系与战略走廊",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "南疆第一江河，从最西北发端，向右下斜贯至东南端",
      },
      {
        "碧龙江", "江", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.5500, 0.8000, true,
        "原文称“几乎贯穿南疆”，无总长度数字",
        "交汇区被赞为南疆钟灵毓秀第一处，聚集柴、巴、夏三家超级势力；第六卷时仍存续并为中心战区",
        CanonPlace::Status::Battlefield,
        CanonPlace::Evidence::A,
        "南疆第二江河，位于赤龙江上游一侧；两江交汇呈“X”形",
      },
      {
        "黄龙江", "江", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4100, 0.7800, true,
        "全长“八千多公里”",
        "方源早年漂流路线所在江；第六卷时仍是南疆重要水系，未见改道或枯竭",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "南疆第三江河，发源黄果山，流经玄冥山、龟背山、青茅山、白骨山、雷磁山后入海",
      },
      {
        "江心漩涡", "漩涡/水险", "南疆地表", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.5500, 0.8300, true,
        "原文称“庞大”，无直径数字",
        "两江交汇形成，水流险恶；第六卷时仍是尸皇芋顶与武家疆域核心坐标",
        CanonPlace::Status::Intact,
        CanonPlace::Evidence::A,
        "赤龙江、黄龙江两江交汇处中心",
      },
      {
        "白相洞天", "洞天", "南疆高空", Domain::NanJiang,
        CanonPlace::Kind::TwoHeavens,
        -1.0, -1.0, false,
        "公共洞天由五相各捐部分仙窍融合，分五块，中央连山脉；白相洞天内有白雪覆盖的山岭",
        "第六卷相关争夺发生时，白相洞天仍可作为进入公共洞天的入口之一；截至第368节未明确毁灭",
        CanonPlace::Status::Ruined,
        CanonPlace::Evidence::A,
        "巡天五相之一白相的仙窍，寄托于“南疆高空某处”",
      },
      {
        "气海洞天", "洞天", "南疆白天", Domain::NanJiang,
        CanonPlace::Kind::TwoHeavens,
        -1.0, -1.0, false,
        "原文未明；内有大量仙材、八转杀招“无数气海”及八转仙蛊“大气”",
        "戚家持续据有并以此为基地；第368节前未述被方源吞并",
        CanonPlace::Status::Absorbed,
        CanonPlace::Evidence::A,
        "气相仙窍，寄托于“南疆白天某处”；戚家大本营",
      },
      {
        "夏槎洞天", "洞天", "南疆高空（宙道）", Domain::NanJiang,
        CanonPlace::Kind::TwoHeavens,
        -1.0, -1.0, false,
        "原文未明；内含八转年华池、八转仙蛊“春”“夏”",
        "第六卷前已被方源吞并，成为其战利品",
        CanonPlace::Status::Absorbed,
        CanonPlace::Evidence::A,
        "夏家夏槎仙窍所化，寄托于南疆高空某处；宙道洞天",
      },
      {
        "狐仙福地", "福地", "中洲天梯山", Domain::ZhongZhou,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明；分南、北、西、中各部分，并非单点小空间",
        "方源完成建设并掌控：南部石人沉眠、血毒棠生灭，北部养长恨蛛，西部花粉兔繁殖，中央保留荡魂山；福地由方源持有",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "原为狐仙意志守护的福地，位于中洲天梯山（位居中洲正中央，高达百万丈，"
        "古时仙凡之梯可上达天庭）；方源在天梯山顶夺得传承后持有，"
        "第六卷中已将之迁入自身仙窍，作为内部福地经营。"
        "【更正】此前标为南疆，与「天梯山位居中洲正中央」相悖",
      },
      {
        "荡魂山", "山（自然秘境）", "狐仙福地内部", Domain::NanJiang,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "粉红水晶山；原文未给长宽数字",
        "一度因福地问题缩小，后经方源用江山如故复原并持续产胆识蛊；第六卷末仍由方源掌控",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "狐仙福地中央；荡魂行宫设于山处",
      },
      {
        "落魄谷", "谷（自然秘境）", "狐仙福地内部", Domain::NanJiang,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "是方源在福地中的既有秘境资源；第六卷时仍归方源掌控",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "与荡魂山并列为狐仙福地内的重要秘境，具体方位原文未明",
      },
      {
        "血湖", "湖", "狐仙福地内部", Domain::NanJiang,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "南部石人沉眠，血毒棠在石人地道中持续生灭；第六卷时仍在福地体系内",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "狐仙福地南部区域",
      },
      {
        "芝林", "森林/资源地", "狐仙福地内部", Domain::NanJiang,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明；福地土质不适合大规模芝林",
        "迁入福地后萎靡，但可自行排毒，可能转为血芝林；第六卷末仍属方源福地资源",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "狐仙福地内；方源曾在南疆碧龙江附近取得灵芝王心",
      },
      {
        "石人地道", "地道/地下区域", "狐仙福地内部", Domain::NanJiang,
        CanonPlace::Kind::InsideCave,
        -1.0, -1.0, false,
        "原文未明",
        "血毒棠在其中生灭，未来可形成血石矿藏；第六卷时仍属方源掌控",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "狐仙福地南部，石人沉眠地底，血湖区域关联处",
      },
      {
        "南疆瘴气界壁", "界壁", "南疆地表外侧", Domain::NanJiang,
        CanonPlace::Kind::Surface,
        0.4656, 0.8708, false,
        "原文未明",
        "是五域互通的天然屏障；五界山脉的紫黑山体为陶铸仿造，不等于真实界壁被毁",
        CanonPlace::Status::Unknown,
        CanonPlace::Evidence::A,
        "南疆与外界五域之间的界壁，并非某一山寨内部",
      },
    };
    return k;
}


std::vector<const CanonPlace*> placesByDomain(Domain d) {
    std::vector<const CanonPlace*> v;
    for (const auto& p : allPlaces())
        if (p.domain == d) v.push_back(&p);
    return v;
}

std::vector<const CanonPlace*> placesByKind(CanonPlace::Kind k) {
    std::vector<const CanonPlace*> v;
    for (const auto& p : allPlaces())
        if (p.kind == k) v.push_back(&p);
    return v;
}

const CanonPlace* findPlace(const std::string& name) {
    for (const auto& p : allPlaces())
        if (p.name == name) return &p;
    return nullptr;
}

} } // namespace gr::canon
