// ============================================================================
//  本文件由 tools/gen_recipe_data.py 自动生成，请勿手工编辑。
//  源数据：蛊真人设定资料库.xlsx【凡蛊总表】【仙蛊总表】
//
//  蛊方来源：
//    · 「炼制方法」列中的合炼公式（含 →，如 月光蛊＋小光蛊×2→月芒蛊）
//    · 「炼制材料（仙材）」列中的材料与组成蛊
//  凡蛊「炼制材料/食物」列中的喂养描述（以…为食、每日…片）已排除，
//  那是维持消耗，不是炼制配方。
//
//  本文件按【蛊名】登记，运行时依名在模板表中查 id ——
//  故增删模板不影响本文件；某组成蛊若未建模板则跳过，
//  蛊方据此判为「残缺」（RecipeIntegrity::Incomplete）。
// ============================================================================
#include "gr/gu/GuWorm.hpp"

#include <vector>
#include <string>

namespace gr {
namespace {

struct RawRecipe {
    const char* outName;
    int         rank;
    const char* compGu[8];
    const char* matNames[8];
    int         matQty[8];
    const char* src;
};

const RawRecipe kRawRecipes[] = {
    {"四味酒虫", 2,
     {"酒虫", "酒虫", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {"酸甜苦辣四味美酒", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·酒虫：2酒虫＋酸甜苦辣四味美酒→四味酒虫"},
    {"月芒蛊", 2,
     {"月光蛊", "小光蛊", "小光蛊", nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "凡蛊总表·小光蛊：月光蛊＋小光蛊×2→月芒蛊"},
    {"黑鬃蛊", 2,
     {"青丝蛊", "黑豕蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "凡蛊总表·青丝蛊：青丝蛊＋黑豕蛊→黑鬃蛊"},
    {"隐鳞蛊", 2,
     {"隐石蛊", "鱼鳞蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "凡蛊总表·隐石蛊：隐石蛊＋鱼鳞蛊→隐鳞蛊"},
    {"白玉蛊", 5,
     {"白豕蛊", "玉皮蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {"野猪牙", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·白豕蛊：白豕蛊＋玉皮蛊＋野猪牙→白玉蛊"},
    {"星镖蛊", 1,
     {nullptr},
     {"顽石", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·星镖蛊 材料栏：顽石"},
    {"星箭骨", 1,
     {nullptr},
     {"顽石", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·星箭骨 材料栏：顽石"},
    {"流星蛊", 1,
     {nullptr},
     {"顽石", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·流星蛊 材料栏：顽石"},
    {"双窍火炉蛊", 2,
     {"单窍火炭蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "凡蛊总表·单窍火炭蛊：单窍火炭蛊→双窍火炉蛊"},
    {"钢鬃蛊", 5,
     {"黑鬃蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "凡蛊总表·钢鬃蛊 材料栏：黑鬃蛊"},
    {"四味酒虫", 2,
     {nullptr},
     {"两只一转酒虫、酸甜苦辣四味美酒", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·四味酒虫 材料栏：两只一转酒虫、酸甜苦辣四味美酒"},
    {"月芒蛊", 2,
     {nullptr},
     {"月光蛊、两只小光蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·月芒蛊 材料栏：月光蛊、两只小光蛊"},
    {"月痕蛊", 2,
     {"月光蛊", "痕石蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "凡蛊总表·月痕蛊：月光蛊＋痕石蛊→月痕蛊"},
    {"月痕蛊", 2,
     {nullptr},
     {"月光蛊、痕石蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·月痕蛊 材料栏：月光蛊、痕石蛊"},
    {"月旋蛊", 2,
     {"月光蛊", "旋风蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "凡蛊总表·月旋蛊：月光蛊＋旋风蛊→月旋蛊"},
    {"月旋蛊", 2,
     {nullptr},
     {"月光蛊、旋风蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·月旋蛊 材料栏：月光蛊、旋风蛊"},
    {"黑鬃蛊", 2,
     {nullptr},
     {"青丝蛊、黑豕蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·黑鬃蛊 材料栏：青丝蛊、黑豕蛊"},
    {"白玉蛊", 5,
     {nullptr},
     {"白豕蛊、玉皮蛊、野猪牙", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·白玉蛊 材料栏：白豕蛊、玉皮蛊、野猪牙"},
    {"天蓬蛊", 4,
     {"白玉蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {"水行防御蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·天蓬蛊：白玉蛊＋水行防御蛊→天蓬蛊"},
    {"天蓬蛊", 4,
     {nullptr},
     {"白玉蛊、一只水行防御蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·天蓬蛊 材料栏：白玉蛊、一只水行防御蛊（名称不详）"},
    {"爱生离", 2,
     {"生息草", "寡妇蛛", "红针蝎", nullptr, nullptr, nullptr, nullptr, nullptr},
     {"爱人之心", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·爱生离：生息草＋寡妇蛛＋红针蝎＋爱人之心→爱生离"},
    {"爱生离", 2,
     {nullptr},
     {"一转生息草、寡妇蛛、红针蝎、爱人之心", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·爱生离 材料栏：一转生息草、寡妇蛛、红针蝎、爱人之心"},
    {"蒙汗蝶", 2,
     {"白虫茧", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "凡蛊总表·白虫茧：白虫茧→蒙汗蝶"},
    {"螺旋骨枪蛊", 2,
     {"骨枪蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "凡蛊总表·螺旋骨枪蛊 材料栏：骨枪蛊"},
    {"冰刃蛊", 2,
     {"冰刀蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "凡蛊总表·冰刃蛊 材料栏：冰刀蛊"},
    {"双窍火炉蛊", 2,
     {nullptr},
     {"单窍火炭蛊、材料不详", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·双窍火炉蛊 材料栏：单窍火炭蛊、材料不详"},
    {"三星洞", 5,
     {nullptr},
     {"真元", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·三星洞 材料栏：真元"},
    {"隐鳞蛊", 2,
     {nullptr},
     {"隐石蛊、鱼鳞蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·隐鳞蛊 材料栏：隐石蛊、鱼鳞蛊"},
    {"鳞甲蛊", 2,
     {nullptr},
     {"鱼鳞蛊、另一材料不详", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·鳞甲蛊 材料栏：鱼鳞蛊、另一材料不详"},
    {"游僵蛊", 3,
     {nullptr},
     {"定时吸血", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·游僵蛊 材料栏：定时吸血"},
    {"癞土蛤蟆", 5,
     {nullptr},
     {"黄泥", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·癞土蛤蟆 材料栏：黄泥"},
    {"宝气黄铜蟾", 5,
     {nullptr},
     {"癞土蛤蟆、其他不详", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·宝气黄铜蟾 材料栏：癞土蛤蟆、其他不详"},
    {"仙人指", 5,
     {nullptr},
     {"种子、种植", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·仙人指 材料栏：种子、种植"},
    {"九叶生机草蛊", 2,
     {nullptr},
     {"水、阳光", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·九叶生机草蛊 材料栏：水、阳光"},
    {"偷袭蛊", 2,
     {nullptr},
     {"明确需要婴儿尸体", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·偷袭蛊 材料栏：明确需要婴儿尸体"},
    {"七香酒虫", 3,
     {"四味酒虫", "四味酒虫", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {"七种香料", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·七香酒虫：2四味酒虫＋七种香料→七香酒虫"},
    {"七香酒虫", 3,
     {nullptr},
     {"两只四味酒虫、七种香料", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·七香酒虫 材料栏：两只四味酒虫、七种香料"},
    {"天蓬蛊", 4,
     {"白玉蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {"一只水行防御蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·天蓬蛊：白玉蛊＋一只水行防御蛊→天蓬蛊"},
    {"天蓬蛊", 4,
     {nullptr},
     {"白玉蛊、水行防御蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·天蓬蛊 材料栏：白玉蛊、水行防御蛊"},
    {"血月蛊", 3,
     {"月芒蛊", "血气蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "凡蛊总表·血月蛊：月芒蛊＋血气蛊→血月蛊"},
    {"血月蛊", 3,
     {nullptr},
     {"月芒蛊、血气蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·血月蛊 材料栏：月芒蛊、血气蛊"},
    {"月影蛊", 3,
     {"幻影月蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "凡蛊总表·月影蛊 材料栏：幻影月蛊"},
    {"力气蛊", 5,
     {nullptr},
     {"风气蛊逆炼", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·力气蛊：风气蛊逆炼→力气蛊"},
    {"力气蛊", 5,
     {"风气蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "凡蛊总表·力气蛊 材料栏：风气蛊"},
    {"胆识蛊", 3,
     {nullptr},
     {"胆石、荡魂山", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·胆识蛊 材料栏：胆石、荡魂山"},
    {"鬼炎蛊", 4,
     {"鬼火蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "凡蛊总表·鬼炎蛊 材料栏：鬼火蛊"},
    {"大蜥屋蛊", 5,
     {nullptr},
     {"蜥屋蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·大蜥屋蛊 材料栏：蜥屋蛊"},
    {"飞僵蛊", 5,
     {"游僵蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "凡蛊总表·飞僵蛊 材料栏：游僵蛊"},
    {"天青狼皮蛊", 5,
     {nullptr},
     {"金背狼皮蛊、其他不详", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·天青狼皮蛊 材料栏：金背狼皮蛊、其他不详"},
    {"狗胆包山蛊", 3,
     {nullptr},
     {"狗胆蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·狗胆包山蛊 材料栏：狗胆蛊"},
    {"狗胆包海蛊", 3,
     {"狗胆包山蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "凡蛊总表·狗胆包海蛊 材料栏：狗胆包山蛊"},
    {"仙人指", 5,
     {nullptr},
     {"种子", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·仙人指 材料栏：种子"},
    {"千年木魅", 5,
     {nullptr},
     {"百年木魅", "千年寿蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 1, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·千年木魅：百年木魅＋千年寿蛊→千年木魅"},
    {"千年木魅", 5,
     {nullptr},
     {"百年木魅、千年寿蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·千年木魅 材料栏：百年木魅、千年寿蛊"},
    {"三心合魂", 3,
     {nullptr},
     {"飞魂蛊、魂链蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·三心合魂 材料栏：飞魂蛊、魂链蛊等"},
    {"金月斩", 3,
     {nullptr},
     {"月手刀、黄金月", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·金月斩 材料栏：月手刀、黄金月"},
    {"刀翅血蝠蛊", 5,
     {nullptr},
     {"血液", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·刀翅血蝠蛊 材料栏：血液"},
    {"人兽葬生蛊", 5,
     {nullptr},
     {"单窍火炭蛊等", "野兽", "处子", nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 1, 1, 0, 0, 0, 0, 0},
     "凡蛊总表·人兽葬生蛊：单窍火炭蛊等＋野兽＋处子→人兽葬生蛊"},
    {"人兽葬生蛊", 5,
     {nullptr},
     {"驭兽蛊、丙等以上资质处子、单窍火炭蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·人兽葬生蛊 材料栏：驭兽蛊、丙等以上资质处子、单窍火炭蛊等"},
    {"骨肉团圆蛊", 5,
     {nullptr},
     {"同胞亲人血肉", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·骨肉团圆蛊 材料栏：同胞亲人血肉"},
    {"九眼酒虫", 4,
     {"七香酒虫", "七香酒虫", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {"九种百兽王眼珠", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·九眼酒虫：2七香酒虫＋九种百兽王眼珠→九眼酒虫"},
    {"九眼酒虫", 4,
     {nullptr},
     {"两只七香酒虫、九种百兽王眼珠", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·九眼酒虫 材料栏：两只七香酒虫、九种百兽王眼珠"},
    {"萍踪浪迹蛊", 5,
     {nullptr},
     {"浪迹蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·萍踪浪迹蛊 材料栏：浪迹蛊"},
    {"浪迹江湖蛊", 5,
     {nullptr},
     {"浪迹蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·浪迹江湖蛊 材料栏：浪迹蛊"},
    {"狗胆包天蛊", 6,
     {"狗胆包海蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "凡蛊总表·狗胆包天蛊 材料栏：狗胆包海蛊"},
    {"千里地狼蛛", 5,
     {nullptr},
     {"土壤", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·千里地狼蛛 材料栏：土壤"},
    {"地藏花王蛊", 5,
     {"地藏花蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "凡蛊总表·地藏花王蛊 材料栏：地藏花蛊"},
    {"泉蛋蛊", 5,
     {nullptr},
     {"特定蛋人", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·泉蛋蛊 材料栏：特定蛋人"},
    {"火蛟蛊", 5,
     {nullptr},
     {"火蛇蛊、火爪蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·火蛟蛊 材料栏：火蛇蛊、火爪蛊"},
    {"苍空蛊", 4,
     {"三转空仓蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "凡蛊总表·苍空蛊 材料栏：三转空仓蛊"},
    {"苍空井蛊", 4,
     {"苍空蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {"天井蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·苍空井蛊：苍空蛊＋天井蛊→苍空井蛊"},
    {"苍空井蛊", 4,
     {nullptr},
     {"苍空蛊、天井蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·苍空井蛊 材料栏：苍空蛊、天井蛊"},
    {"推杯换盏蛊", 5,
     {nullptr},
     {"金杯蛊", "银盏蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 1, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·金杯银盏蛊：金杯蛊＋银盏蛊→推杯换盏蛊"},
    {"金杯银盏蛊", 4,
     {nullptr},
     {"金杯蛊、银盏蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·金杯银盏蛊 材料栏：金杯蛊、银盏蛊"},
    {"推杯换盏蛊", 5,
     {nullptr},
     {"金杯银盏", "旁推侧引", "移步换形", nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 1, 1, 0, 0, 0, 0, 0},
     "凡蛊总表·旁推侧引蛊：金杯银盏＋旁推侧引＋移步换形→推杯换盏"},
    {"碧空蛊", 5,
     {nullptr},
     {"碧空蛊、定星蛊、太光蛊、三更蛊、百战不殆蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·碧空蛊 材料栏：碧空蛊、定星蛊、太光蛊、三更蛊、百战不殆蛊等"},
    {"洞地蛊", 5,
     {nullptr},
     {"元石", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·洞地蛊 材料栏：元石（年耗二十万）"},
    {"血颅蛊", 6,
     {"血亲", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "凡蛊总表·血颅蛊 材料栏：血亲"},
    {"竹君子", 5,
     {nullptr},
     {"真诚", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·竹君子 材料栏：真诚（抽象食料）"},
    {"第二空窍蛊", 6,
     {"紫晶舍利蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "凡蛊总表·第二空窍蛊 材料栏：紫晶舍利蛊等（材料体系）"},
    {"吞江蟾", 5,
     {nullptr},
     {"水", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·吞江蟾 材料栏：水"},
    {"血滴子", 5,
     {nullptr},
     {"蛊师鲜血", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·血滴子 材料栏：蛊师鲜血"},
    {"白相仙蛇蛊", 5,
     {nullptr},
     {"元泉水", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·白相仙蛇蛊 材料栏：元泉水"},
    {"血河蟒", 5,
     {nullptr},
     {"血液", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·血河蟒 材料栏：血液"},
    {"血鬼尸蛊", 5,
     {"游僵蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "凡蛊总表·血鬼尸蛊 材料栏：游僵蛊"},
    {"碧空蛊", 5,
     {nullptr},
     {"碧空蛊、定星蛊、太光蛊、三更、百战不殆", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·碧空蛊 材料栏：碧空蛊、定星蛊、太光蛊、三更、百战不殆"},
    {"金刚飞蜈", 5,
     {nullptr},
     {"蜈蚣蛊材、炭火", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·金刚飞蜈 材料栏：蜈蚣蛊材、炭火"},
    {"推杯换盏蛊", 5,
     {nullptr},
     {"金杯蛊、银盏蛊、旁推侧引蛊、移步换形蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·推杯换盏蛊 材料栏：金杯蛊、银盏蛊、旁推侧引蛊、移步换形蛊"},
    {"宝月光王蛊", 5,
     {"月光蛊", "玉皮蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "凡蛊总表·宝月光王蛊：月光蛊＋玉皮蛊路线→月霓裳→宝月光王蛊"},
    {"宝月光王蛊", 5,
     {nullptr},
     {"月光蛊、玉皮蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·宝月光王蛊 材料栏：月光蛊、玉皮蛊"},
    {"月霓裳", 5,
     {"玉皮蛊", "月光蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "凡蛊总表·月霓裳：玉皮蛊＋月光蛊→月霓裳"},
    {"月霓裳", 5,
     {nullptr},
     {"玉皮蛊、月光蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·月霓裳 材料栏：玉皮蛊、月光蛊"},
    {"至亲血虫蛊", 5,
     {nullptr},
     {"至亲之血", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·至亲血虫蛊 材料栏：至亲之血"},
    {"地听肉耳草", 5,
     {nullptr},
     {"参须", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·地听肉耳草 材料栏：参须"},
    {"骨竹蛊", 5,
     {nullptr},
     {"白骨", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·骨竹蛊 材料栏：白骨"},
    {"战骨车轮", 5,
     {nullptr},
     {"白骨", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·战骨车轮 材料栏：白骨"},
    {"人兽葬生蛊", 5,
     {nullptr},
     {"驭兽蛊、处子、单窍火炭蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·人兽葬生蛊 材料栏：驭兽蛊、处子、单窍火炭蛊等"},
    {"酒囊花蛊", 5,
     {nullptr},
     {"真元", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·酒囊花蛊 材料栏：真元"},
    {"饭袋草蛊", 5,
     {nullptr},
     {"真元", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·饭袋草蛊 材料栏：真元"},
    {"长恨蛛", 1,
     {nullptr},
     {"潜沙蛛后血肉；辅料未列。", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·长恨蛛 材料栏：潜沙蛛后血肉；辅料未列。"},
    {"蜘蛛凡蛊", 1,
     {nullptr},
     {"潜沙蛛后血肉；具体蛊材不详。", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·蜘蛛凡蛊 材料栏：潜沙蛛后血肉；具体蛊材不详。"},
    {"胆石", 1,
     {nullptr},
     {"魂魄、荡魂山地脉", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·胆石 材料栏：魂魄、荡魂山地脉"},
    {"蛋人相关泉蛋蛊", 1,
     {nullptr},
     {"特定蛋人", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "凡蛊总表·蛋人相关泉蛋蛊 材料栏：特定蛋人"},
    {"天元宝君莲蛊", 4,
     {nullptr},
     {"废元泉", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·天元宝君莲蛊 材料栏：废元泉等"},
    {"天元宝王莲蛊", 5,
     {nullptr},
     {"废元泉", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·天元宝王莲蛊 材料栏：废元泉等"},
    {"第二空窍蛊", 6,
     {nullptr},
     {"兽力胎盘蛊、蛊师人窍、黄金紫晶舍利蛊、六转神游蛊、八百年寿蛊及上百种仙材", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·第二空窍蛊 材料栏：兽力胎盘蛊、蛊师人窍、黄金紫晶舍利蛊、六转神游蛊、八百年寿蛊及上百种仙材"},
    {"神游蛊", 6,
     {nullptr},
     {"四种极品美酒", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·神游蛊 材料栏：四种极品美酒"},
    {"血神子", 6,
     {"血亲", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "仙蛊总表·血神子 材料栏：血亲"},
    {"吃力蛊", 6,
     {nullptr},
     {"力道兽肉或果蔬", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·吃力蛊 材料栏：力道兽肉或果蔬"},
    {"飞熊虚影蛊", 6,
     {nullptr},
     {"飞熊皮、血、骨、魂", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·飞熊虚影蛊 材料栏：飞熊皮、血、骨、魂"},
    {"定仙游", 6,
     {nullptr},
     {"神游蛊、碧空蛊、定星蛊、荣耀之光、三更蛊、百战不殆蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·定仙游 材料栏：神游蛊、碧空蛊、定星蛊、荣耀之光、三更蛊、百战不殆蛊"},
    {"妇人心蛊", 7,
     {nullptr},
     {"妇人心脏", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·妇人心蛊 材料栏：妇人心脏等"},
    {"近水楼台", 7,
     {nullptr},
     {"水乳交融仙蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·近水楼台 材料栏：水乳交融仙蛊"},
    {"煮运锅", 8,
     {nullptr},
     {"狗屎运、气运、察运、连运、时运、煮、铁壁", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·煮运锅 材料栏：狗屎运、气运、察运、连运、时运、煮、铁壁"},
    {"万年斗飞车", 8,
     {nullptr},
     {"似水流年、防备、斗", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·万年斗飞车 材料栏：似水流年、防备、斗等"},
    {"玉清滴风小竹楼", 8,
     {nullptr},
     {"两只八转风道仙蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·玉清滴风小竹楼 材料栏：两只八转风道仙蛊"},
    {"神帝城", 8,
     {nullptr},
     {"豆神宫、帝君城", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·神帝城 材料栏：豆神宫、帝君城"},
    {"八十八角真阳楼", 8,
     {nullptr},
     {"排难仙蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·八十八角真阳楼 材料栏：排难仙蛊"},
    {"狗屎运蛊", 8,
     {nullptr},
     {"天残犬、星荒犬、玉像残白犬等六种犬类荒兽粪便", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·狗屎运蛊 材料栏：天残犬、星荒犬、玉像残白犬等六种犬类荒兽粪便"},
    {"衍化蛊", 9,
     {nullptr},
     {"人祖十子尸体、人祖自身", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·衍化蛊 材料栏：人祖十子尸体、人祖自身"},
    {"天元宝皇莲", 9,
     {nullptr},
     {"废天然元泉等大量仙材", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·天元宝皇莲 材料栏：废天然元泉等大量仙材"},
    {"四元方悔血炼池", 9,
     {nullptr},
     {"升炼、水炼、悔、血本、年华分池、炼海雏形、早秋、中秋、晚秋", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·四元方悔血炼池 材料栏：升炼、水炼、悔、血本、年华分池、炼海雏形、早秋、中秋、晚秋等"},
    {"监天塔", 9,
     {"宿命蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "仙蛊总表·监天塔 材料栏：宿命蛊"},
    {"天机蛊", 9,
     {"天道仙材", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "仙蛊总表·天机蛊 材料栏：天道仙材"},
    {"未名犬类荒兽粪便仙材", 1,
     {nullptr},
     {"天残犬、星荒犬、玉像残白犬等六种犬类荒兽粪便", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·未名犬类荒兽粪便仙材 材料栏：天残犬、星荒犬、玉像残白犬等六种犬类荒兽粪便"},
    {"荣耀之光", 1,
     {nullptr},
     {"太古青天中的荣耀之光", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·荣耀之光 材料栏：太古青天中的荣耀之光"},
    {"天然元泉", 1,
     {nullptr},
     {"多口天然元泉", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·天然元泉 材料栏：多口天然元泉"},
    {"逆炼材料（风气蛊）", 1,
     {"风气蛊", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr},
     {nullptr}, {0},
     "仙蛊总表·逆炼材料（风气蛊） 材料栏：风气蛊"},
    {"犬类荒兽粪便", 1,
     {nullptr},
     {"六种犬类荒兽粪便", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·犬类荒兽粪便 材料栏：六种犬类荒兽粪便"},
    {"对应高山/海洋", 1,
     {nullptr},
     {"高山、海洋", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·对应高山/海洋 材料栏：高山、海洋"},
    {"积德蛊", 1,
     {nullptr},
     {"善行", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·积德蛊 材料栏：善行"},
    {"起死回生蛊", 1,
     {nullptr},
     {"仙僵、生死纠缠之物", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·起死回生蛊 材料栏：仙僵、生死纠缠之物"},
    {"电脑蛊", 1,
     {nullptr},
     {"智珠草；其余不详", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·电脑蛊 材料栏：智珠草（已确认）；其余不详"},
    {"赌蛊", 1,
     {nullptr},
     {"天外偷道道痕", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}, {1, 0, 0, 0, 0, 0, 0, 0},
     "仙蛊总表·赌蛊 材料栏：天外偷道道痕"},
};

} // namespace

// 依蛊名在模板表中查 id；查不到返回 0（该组成蛊缺失 → 蛊方残缺）
static GuId idOf(const std::vector<GuTemplate>& tpls, const char* n) {
    if (!n || !*n) return 0;
    for (const auto& t : tpls) if (t.name == n) return t.id;
    return 0;
}

std::vector<GuRecipe> buildCanonRecipeData(
        const std::vector<GuTemplate>& tpls, RecipeId idBase) {
    std::vector<GuRecipe> v;
    RecipeId id = idBase;
    for (const auto& r : kRawRecipes) {
        GuRecipe rec;
        rec.id         = id++;
        rec.name       = r.outName;
        rec.targetRank = static_cast<Rank>(r.rank);
        rec.integrity  = RecipeIntegrity::Complete;
        bool missing   = false;
        for (const char* n : r.compGu) {
            if (!n || !*n) continue;
            const GuId gid = idOf(tpls, n);
            if (gid == 0) { missing = true; continue; }
            rec.componentGu.push_back(gid);
        }
        for (int i = 0; i < 8; ++i) {
            if (!r.matNames[i] || !*r.matNames[i]) continue;
            rec.materials.push_back({r.matNames[i],
                                    static_cast<double>(r.matQty[i])});
        }
        //  组成蛊有缺失 → 判为残缺蛊方，只出残次品（炼蛊铁律）
        if (missing) rec.integrity = RecipeIntegrity::Incomplete;
        rec.requiredDao     = DaoLevel::Entry;
        rec.requiredEssence = 0.0;
        rec.canon          = true;
        rec.source         = r.src;
        //  流派与目标蛊一致
        for (const auto& t : tpls)
            if (t.name == r.outName) { rec.dao = t.dao; break; }
        v.push_back(std::move(rec));
    }
    return v;
}

} // namespace gr
